version: 0.2

phases:
  install:
    commands:
      - printenv
      - ls -la
      - git log --pretty=format:"%cd %h %cn %s"

  pre_build:
    commands:
       - echo 11111111

  build:
    commands:
       - echo 2222222

artifacts:
  files:
    - '**/*'

