version: 0.2

phases:
  install:
    commands:
      - printenv

  pre_build:
    commands:
       - echo 11111111

  build:
    commands:
       - echo 333tag333
       - echo 2222222

artifacts:
  files:
    - '**/*'

