version: 0.2

phases:
  install:
    commands:
      - printenv
      - ls -la
      - file *
      - git diff --name-status ${CODEBUILD_SOURCE_VERSION}^

  pre_build:
    commands:
       - echo 11111111

  build:
    commands:
       - echo 2222222

artifacts:
  files:
    - '**/*'

